create table cuisine (id integer not null auto_increment, cuisine_name varchar(255), primary key (id)) engine=InnoDB;
create table dish (id integer not null auto_increment, description varchar(255), dish_name varchar(255), price double precision, primary key (id)) engine=InnoDB;
create table dish_ingredient (dish_id integer not null, ingredient_id integer not null, primary key (dish_id, ingredient_id)) engine=InnoDB;
create table ingredient (id integer not null auto_increment, ingredient_name varchar(255), weight double precision, primary key (id)) engine=InnoDB;
create table menu (id integer not null auto_increment, description varchar(255), dish_id integer, primary key (id)) engine=InnoDB;
create table restaurant (id integer not null auto_increment, address varchar(255), description varchar(255), restaurant_name varchar(255), menu_id integer, primary key (id)) engine=InnoDB;
create table user (id integer not null auto_increment, first_name varchar(255), last_name varchar(255), login varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table dish_ingredient add constraint FKlsik2ca5etotku9wviwcnsbu4 foreign key (ingredient_id) references ingredient (id);
alter table dish_ingredient add constraint FKb0mfoikuh0kjw66vsssyqseo foreign key (dish_id) references dish (id);
alter table menu add constraint FKbm92hs82t812cdhtj0l0ok6kl foreign key (dish_id) references dish (id);
alter table restaurant add constraint FKooiid4751i6wv4ebwbi6gjfr3 foreign key (menu_id) references menu (id);
create table cuisine_restaurant (cuisine_id integer not null, restaurant_id integer not null, primary key (cuisine_id, restaurant_id)) engine=InnoDB;
alter table cuisine_restaurant add constraint FK27icvcide65wdspkujtlgv3ix foreign key (restaurant_id) references restaurant (id);
alter table cuisine_restaurant add constraint FKiuejt4vtlre889uo2ia009pem foreign key (cuisine_id) references cuisine (id);